chore: reject promise with error when encountered
Otherwise you get this sort of thing which is less helpful:

```
      if (res.statusCode !== 200) {
              ^

TypeError: Cannot read property 'statusCode' of undefined
```